/**
 * Generates `client/src/renderer/lib/emoji-data.ts` from the Unicode
 * `emoji-test.txt` (UTS #51) so the icon picker offers the FULL emoji set
 * grouped by the classic CLDR categories (08-ui-spec.md §6.8).
 *
 * Usage:
 *   node scripts/gen-emoji.mjs < path/to/emoji-test.txt
 *   (or: node scripts/gen-emoji.mjs path/to/emoji-test.txt)
 *
 * The generated file is committed; the script exists for regeneration when
 * a newer Unicode release ships. Skin-tone variants (1F3FB–1F3FF) are
 * omitted — they are duplicates of the base emoji with a modifier.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/** English group name → Russian UI label. */
const GROUP_NAMES_RU = {
  'Smileys & Emotion': 'Смайлики и эмоции',
  'People & Body': 'Люди и тело',
  'Animals & Nature': 'Животные и природа',
  'Food & Drink': 'Еда и напитки',
  'Travel & Places': 'Путешествия и места',
  Activities: 'Занятия',
  Objects: 'Предметы',
  Symbols: 'Символы',
  Flags: 'Флаги',
};

/** Skin-tone modifier code points — variants of the base emoji (1F3FB–1F3FF). */
const SKIN_TONES = new Set(['1F3FB', '1F3FC', '1F3FD', '1F3FE', '1F3FF']);

/** Parse emoji-test.txt into [{ name, items }] (English group names). */
function parse(text) {
  const groups = [];
  let current = null;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    const groupMatch = /^# group: (.+)$/.exec(line);
    if (groupMatch) {
      current = { name: groupMatch[1], items: [] };
      groups.push(current);
      continue;
    }
    const statusMatch = /^([0-9A-F ]+); fully-qualified\s+#/.exec(line);
    if (!statusMatch || current === null) continue;
    const codepoints = statusMatch[1].trim().split(/\s+/);
    // Skip skin-tone variants: the same picture repeated five times.
    if (codepoints.some((cp) => SKIN_TONES.has(cp))) continue;
    const glyph = codepoints.map((cp) => String.fromCodePoint(parseInt(cp, 16))).join('');
    current.items.push(glyph);
  }
  return groups;
}

/** Render the generated TypeScript module. */
function render(groups, version) {
  const lines = [];
  lines.push('/**');
  lines.push(` * Full emoji list grouped by CLDR categories (Unicode ${version}).`);
  lines.push(' *');
  lines.push(' * GENERATED by scripts/gen-emoji.mjs from emoji-test.txt — do not edit');
  lines.push(' * by hand. Skin-tone variants are omitted (duplicates of the base emoji).');
  lines.push(' */');
  lines.push('');
  lines.push('export interface EmojiGroup {');
  lines.push("  /** Russian label shown in the picker (08-ui-spec.md §6.8). */");
  lines.push('  name: string;');
  lines.push('  /** Emoji glyphs of the group. */');
  lines.push('  items: string[];');
  lines.push('}');
  lines.push('');
  lines.push('export const EMOJI_GROUPS: EmojiGroup[] = [');
  for (const g of groups) {
    const ru = GROUP_NAMES_RU[g.name] ?? g.name;
    const rows = [];
    for (let i = 0; i < g.items.length; i += 16) {
      const chunk = g.items.slice(i, i + 16).map((s) => `'${s}'`).join(', ');
      rows.push(`    ${chunk},`);
    }
    lines.push(`  { name: '${ru}', items: [`);
    lines.push(...rows);
    lines.push('  ],');
    lines.push(`  // ${g.name} (${g.items.length})`);
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  return lines.join('\n');
}

// --- main -------------------------------------------------------------------

const input = process.argv[2] ?? process.stdin.fd;
const text =
  process.argv[2] !== undefined ? readFileSync(input, 'utf8') : readFileSync(0, 'utf8');

const versionMatch = /^# Version: (.+)$/m.exec(text);
const version = versionMatch?.[1] ?? 'unknown';
const groups = parse(text).filter((g) => g.name !== 'Component' && g.items.length > 0);

const outDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'renderer', 'lib');
const outFile = path.join(outDir, 'emoji-data.ts');
writeFileSync(outFile, render(groups, version), 'utf8');

console.log(`emoji-data.ts: ${groups.length} groups, ${groups.reduce((n, g) => n + g.items.length, 0)} emoji (Unicode ${version})`);
