/**
 * Каталог имён иконок Lucide, допустимых для вида иконки мысли
 * "icon_kind='icon'" (ADR 2b655b29, требование ead91183, задача 610a440e).
 *
 * ЕДИНЫЙ источник допустимых имён: сервер валидирует поле "icon" по нему,
 * клиент (вкладка «Библиотека» диалога выбора иконки) предлагает ровно эти
 * имена. Файл СГЕНЕРИРОВАН скриптом shared/scripts/gen-icon-catalog.mjs
 * из пакета lucide 1.52.0 (1866 имён) — правки
 * вручную затрутся при перегенерации.
 *
 * Имена — kebab-case, псевдонимы (несколько экспортов одной геометрии)
 * сведены к одному каноническому имени — то же правило, что у фасада
 * client/src/renderer/lib/ui/icon.ts (buildIconCatalog); синхронность
 * сторон стережёт client/tests/guard-icon-catalog.test.ts.
 *
 * Рядом с каноническими именами собран карта псевдонимов
 * ICON_LIBRARY_ALIASES (псевдоним → каноническое имя, ошибка 08b90470):
 * поиск во вкладке «Библиотека» находит значок и по псевдониму, а отдаёт
 * каноническое имя — единственное, что принимает сервер и хранит БД.
 *
 * Перегенерировать после обновления lucide:
 *   node shared/scripts/gen-icon-catalog.mjs
 */

/** Допустимые имена иконок каталога Lucide (kebab-case, отсортированы). */
export const ICON_LIBRARY_NAMES: readonly string[] = [
  'a-arrow-down',
  'a-arrow-up',
  'a-large-small',
  'accessibility',
  'activity',
  'activity-square',
  'ad',
  'air-vent',
  'airplay',
  'alarm-check',
  'alarm-clock',
  'alarm-clock-minus',
  'alarm-clock-off',
  'alarm-clock-plus',
  'alarm-smoke',
  'album',
  'alert-circle',
  'alert-octagon',
  'alert-triangle',
  'align-center',
  'align-center-horizontal',
  'align-center-vertical',
  'align-end-horizontal',
  'align-end-vertical',
  'align-horizontal-distribute-center',
  'align-horizontal-distribute-end',
  'align-horizontal-distribute-start',
  'align-horizontal-justify-center',
  'align-horizontal-justify-end',
  'align-horizontal-justify-start',
  'align-horizontal-space-around',
  'align-horizontal-space-between',
  'align-justify',
  'align-left',
  'align-right',
  'align-start-horizontal',
  'align-start-vertical',
  'align-vertical-distribute-center',
  'align-vertical-distribute-end',
  'align-vertical-distribute-start',
  'align-vertical-justify-center',
  'align-vertical-justify-end',
  'align-vertical-justify-start',
  'align-vertical-space-around',
  'align-vertical-space-between',
  'ambulance',
  'ampersand',
  'ampersands',
  'amphora',
  'anchor',
  'angle',
  'angry',
  'annoyed',
  'antenna',
  'anvil',
  'aperture',
  'app-window',
  'app-window-mac',
  'apple',
  'archive',
  'archive-restore',
  'archive-x',
  'area-chart',
  'armchair',
  'armenian-dram',
  'arrow-big-down',
  'arrow-big-down-dash',
  'arrow-big-left',
  'arrow-big-left-dash',
  'arrow-big-right',
  'arrow-big-right-dash',
  'arrow-big-up',
  'arrow-big-up-dash',
  'arrow-down',
  'arrow-down-01',
  'arrow-down-10',
  'arrow-down-az',
  'arrow-down-circle',
  'arrow-down-from-line',
  'arrow-down-left',
  'arrow-down-left-from-circle',
  'arrow-down-left-from-square',
  'arrow-down-left-square',
  'arrow-down-narrow-wide',
  'arrow-down-right',
  'arrow-down-right-from-circle',
  'arrow-down-right-from-square',
  'arrow-down-right-square',
  'arrow-down-square',
  'arrow-down-to-dot',
  'arrow-down-to-line',
  'arrow-down-up',
  'arrow-down-wide-narrow',
  'arrow-down-za',
  'arrow-left',
  'arrow-left-circle',
  'arrow-left-from-line',
  'arrow-left-right',
  'arrow-left-square',
  'arrow-left-to-line',
  'arrow-right',
  'arrow-right-circle',
  'arrow-right-from-line',
  'arrow-right-left',
  'arrow-right-square',
  'arrow-right-to-line',
  'arrow-up',
  'arrow-up-01',
  'arrow-up-10',
  'arrow-up-az',
  'arrow-up-circle',
  'arrow-up-down',
  'arrow-up-from-dot',
  'arrow-up-from-line',
  'arrow-up-left',
  'arrow-up-left-from-circle',
  'arrow-up-left-from-square',
  'arrow-up-left-square',
  'arrow-up-narrow-wide',
  'arrow-up-right',
  'arrow-up-right-from-circle',
  'arrow-up-right-from-square',
  'arrow-up-right-square',
  'arrow-up-square',
  'arrow-up-to-line',
  'arrow-up-wide-narrow',
  'arrow-up-za',
  'arrows-up-from-line',
  'asterisk',
  'asterisk-square',
  'astroid',
  'at-sign',
  'atom',
  'audio-lines',
  'audio-lines-off',
  'audio-lines-x',
  'audio-waveform',
  'award',
  'axe',
  'axis-3-d',
  'baby',
  'backpack',
  'badge',
  'badge-alert',
  'badge-cent',
  'badge-check',
  'badge-dollar-sign',
  'badge-euro',
  'badge-help',
  'badge-indian-rupee',
  'badge-info',
  'badge-japanese-yen',
  'badge-minus',
  'badge-percent',
  'badge-plus',
  'badge-pound-sterling',
  'badge-russian-ruble',
  'badge-swiss-franc',
  'badge-turkish-lira',
  'badge-x',
  'baggage-claim',
  'balloon',
  'ban',
  'banana',
  'bandage',
  'bangladeshi-taka',
  'banknote',
  'banknote-arrow-down',
  'banknote-arrow-up',
  'banknote-check',
  'banknote-x',
  'bar-chart',
  'bar-chart-2',
  'bar-chart-3',
  'bar-chart-4',
  'bar-chart-big',
  'bar-chart-horizontal',
  'bar-chart-horizontal-big',
  'barcode',
  'barrel',
  'baseline',
  'bath',
  'battery',
  'battery-charging',
  'battery-full',
  'battery-low',
  'battery-medium',
  'battery-plus',
  'battery-warning',
  'beaker',
  'bean',
  'bean-off',
  'bed',
  'bed-double',
  'bed-single',
  'beef',
  'beef-off',
  'beer',
  'beer-off',
  'bell',
  'bell-check',
  'bell-dot',
  'bell-electric',
  'bell-minus',
  'bell-off',
  'bell-plus',
  'bell-ring',
  'between-horizonal-end',
  'between-horizonal-start',
  'between-vertical-end',
  'between-vertical-start',
  'biceps-flexed',
  'bike',
  'binary',
  'binoculars',
  'biohazard',
  'bird',
  'birdhouse',
  'bitcoin',
  'blend',
  'blender',
  'blinds',
  'blocks',
  'bluetooth',
  'bluetooth-connected',
  'bluetooth-off',
  'bluetooth-searching',
  'bold',
  'bolt',
  'bomb',
  'bone',
  'bone-fracture',
  'book',
  'book-a',
  'book-alert',
  'book-audio',
  'book-bookmark',
  'book-check',
  'book-copy',
  'book-dashed',
  'book-down',
  'book-headphones',
  'book-heart',
  'book-image',
  'book-key',
  'book-lock',
  'book-minus',
  'book-open',
  'book-open-check',
  'book-open-text',
  'book-plus',
  'book-search',
  'book-text',
  'book-type',
  'book-up',
  'book-up-2',
  'book-user',
  'book-x',
  'bookmark',
  'bookmark-check',
  'bookmark-minus',
  'bookmark-off',
  'bookmark-plus',
  'bookmark-x',
  'boom-box',
  'bot',
  'bot-message-square',
  'bot-off',
  'bottle-wine',
  'bow-arrow',
  'box',
  'box-select',
  'boxes',
  'braces',
  'brackets',
  'brain',
  'brain-circuit',
  'brain-cog',
  'brick-wall',
  'brick-wall-fire',
  'brick-wall-shield',
  'bridge',
  'briefcase',
  'briefcase-business',
  'briefcase-conveyor-belt',
  'briefcase-medical',
  'briefcase-plus',
  'bring-to-front',
  'broccoli',
  'broom',
  'broom-sparkles',
  'brush',
  'brush-cleaning',
  'bubbles',
  'bug',
  'bug-off',
  'bug-play',
  'building',
  'building-2',
  'building-complex-plus',
  'bus',
  'bus-front',
  'cable',
  'cable-car',
  'cake',
  'cake-slice',
  'calculator',
  'calendar',
  'calendar-1',
  'calendar-arrow-down',
  'calendar-arrow-up',
  'calendar-check',
  'calendar-check-2',
  'calendar-chevrons-right',
  'calendar-clock',
  'calendar-cog',
  'calendar-days',
  'calendar-fold',
  'calendar-heart',
  'calendar-minus',
  'calendar-minus-2',
  'calendar-off',
  'calendar-plus',
  'calendar-plus-2',
  'calendar-range',
  'calendar-search',
  'calendar-sync',
  'calendar-x',
  'calendar-x-2',
  'calendars',
  'camera',
  'camera-off',
  'can',
  'can-soda',
  'candlestick-chart',
  'candy',
  'candy-cane',
  'candy-off',
  'cannabis',
  'cannabis-off',
  'captions',
  'captions-off',
  'car',
  'car-battery',
  'car-front',
  'car-taxi-front',
  'caravan',
  'card-sim',
  'carrot',
  'carton',
  'carton-off',
  'case-lower',
  'case-sensitive',
  'case-upper',
  'cassette-tape',
  'cast',
  'castle',
  'cat',
  'cctv',
  'cctv-off',
  'chart-bar-decreasing',
  'chart-bar-increasing',
  'chart-bar-stacked',
  'chart-column-decreasing',
  'chart-column-stacked',
  'chart-gantt',
  'chart-line',
  'chart-network',
  'chart-no-axes-column-decreasing',
  'chart-no-axes-combined',
  'chart-no-axes-gantt',
  'chart-pie',
  'chart-scatter',
  'chart-spline',
  'check',
  'check-check',
  'check-circle',
  'check-circle-2',
  'check-line',
  'check-square',
  'check-square-2',
  'chef-hat',
  'cherry',
  'chess-bishop',
  'chess-king',
  'chess-knight',
  'chess-pawn',
  'chess-queen',
  'chess-rook',
  'chevron-down',
  'chevron-down-circle',
  'chevron-down-square',
  'chevron-first',
  'chevron-last',
  'chevron-left',
  'chevron-left-circle',
  'chevron-left-square',
  'chevron-right',
  'chevron-right-circle',
  'chevron-right-square',
  'chevron-up',
  'chevron-up-circle',
  'chevron-up-square',
  'chevrons-down',
  'chevrons-down-up',
  'chevrons-left',
  'chevrons-left-right',
  'chevrons-left-right-ellipsis',
  'chevrons-right',
  'chevrons-right-left',
  'chevrons-up',
  'chevrons-up-down',
  'church',
  'cigarette',
  'cigarette-off',
  'circle',
  'circle-dashed',
  'circle-dashed-check',
  'circle-divide',
  'circle-dollar-sign',
  'circle-dot',
  'circle-dot-dashed',
  'circle-ellipsis',
  'circle-equal',
  'circle-euro',
  'circle-fading-arrow-up',
  'circle-fading-plus',
  'circle-gauge',
  'circle-help',
  'circle-minus',
  'circle-off',
  'circle-parking',
  'circle-parking-off',
  'circle-pause',
  'circle-percent',
  'circle-pile',
  'circle-play',
  'circle-plus',
  'circle-pound-sterling',
  'circle-power',
  'circle-slash',
  'circle-slash-2',
  'circle-small',
  'circle-star',
  'circle-stop',
  'circle-user',
  'circle-user-round',
  'circle-x',
  'circuit-board',
  'citrus',
  'clapperboard',
  'clef-alto',
  'clef-bass',
  'clef-treble',
  'clipboard',
  'clipboard-check',
  'clipboard-clock',
  'clipboard-copy',
  'clipboard-edit',
  'clipboard-list',
  'clipboard-minus',
  'clipboard-paste',
  'clipboard-pen-line',
  'clipboard-plus',
  'clipboard-type',
  'clipboard-x',
  'clock',
  'clock-1',
  'clock-10',
  'clock-11',
  'clock-12',
  'clock-2',
  'clock-3',
  'clock-4',
  'clock-5',
  'clock-6',
  'clock-7',
  'clock-8',
  'clock-9',
  'clock-alert',
  'clock-arrow-down',
  'clock-arrow-left',
  'clock-arrow-right',
  'clock-arrow-up',
  'clock-check',
  'clock-fading',
  'clock-plus',
  'closed-caption',
  'cloud',
  'cloud-alert',
  'cloud-backup',
  'cloud-check',
  'cloud-cog',
  'cloud-download',
  'cloud-drizzle',
  'cloud-fog',
  'cloud-hail',
  'cloud-lightning',
  'cloud-moon',
  'cloud-moon-rain',
  'cloud-off',
  'cloud-rain',
  'cloud-rain-wind',
  'cloud-snow',
  'cloud-sun',
  'cloud-sun-rain',
  'cloud-sync',
  'cloud-upload',
  'cloudy',
  'clover',
  'club',
  'code',
  'code-2',
  'code-square',
  'coffee',
  'cog',
  'coins',
  'columns',
  'columns-3',
  'columns-3-cog',
  'columns-4',
  'combine',
  'command',
  'compass',
  'component',
  'computer',
  'concierge-bell',
  'cone',
  'construction',
  'contact',
  'contact-2',
  'container',
  'contrast',
  'cookie',
  'cooking-pot',
  'copy',
  'copy-check',
  'copy-minus',
  'copy-plus',
  'copy-slash',
  'copy-x',
  'copyleft',
  'copyright',
  'corner-down-left',
  'corner-down-right',
  'corner-left-down',
  'corner-left-up',
  'corner-right-down',
  'corner-right-up',
  'corner-up-left',
  'corner-up-right',
  'cpu',
  'creative-commons',
  'credit-card',
  'credit-card-check',
  'credit-card-minus',
  'credit-card-plus',
  'credit-card-reader',
  'credit-card-x',
  'croissant',
  'crop',
  'cross',
  'crosshair',
  'crown',
  'cuboid',
  'cup-soda',
  'cupcake',
  'currency',
  'cylinder',
  'dam',
  'database',
  'database-arrow-down',
  'database-arrow-up',
  'database-backup',
  'database-check',
  'database-minus',
  'database-plus',
  'database-search',
  'database-x',
  'database-zap',
  'decimals-arrow-left',
  'decimals-arrow-right',
  'delete',
  'dessert',
  'diameter',
  'diamond',
  'diamond-minus',
  'diamond-percent',
  'diamond-plus',
  'dice-1',
  'dice-2',
  'dice-3',
  'dice-4',
  'dice-5',
  'dice-6',
  'dices',
  'diff',
  'disc',
  'disc-2',
  'disc-3',
  'disc-album',
  'divide',
  'divide-square',
  'dna',
  'dna-off',
  'dock',
  'dog',
  'dollar-sign',
  'dome',
  'donut',
  'door-closed',
  'door-closed-cog',
  'door-closed-locked',
  'door-closed-package',
  'door-open',
  'door-stairwell',
  'dot',
  'dot-square',
  'download',
  'drafting-compass',
  'drama',
  'drill',
  'drone',
  'droplet',
  'droplet-off',
  'droplets',
  'drum',
  'drumstick',
  'dumbbell',
  'ear',
  'ear-off',
  'earth',
  'earth-lock',
  'eclipse',
  'edit',
  'edit-2',
  'edit-3',
  'egg',
  'egg-fried',
  'egg-off',
  'eject',
  'ellipse',
  'ellipsis',
  'ellipsis-vertical',
  'engine',
  'equal',
  'equal-approximately',
  'equal-approximately-not',
  'equal-not',
  'equal-square',
  'eraser',
  'ethernet-port',
  'euro',
  'ev-charger',
  'expand',
  'external-link',
  'eye',
  'eye-closed',
  'eye-dashed',
  'eye-off',
  'face-grinning',
  'face-neutral',
  'face-slightly-frowning',
  'face-slightly-smiling',
  'face-slightly-smiling-plus',
  'factory',
  'fan',
  'fast-forward',
  'faucet',
  'feather',
  'fence',
  'ferris-wheel',
  'file',
  'file-archive',
  'file-audio',
  'file-axis-3-d',
  'file-badge',
  'file-bar-chart',
  'file-bar-chart-2',
  'file-box',
  'file-braces',
  'file-braces-corner',
  'file-chart-line',
  'file-chart-pie',
  'file-check',
  'file-check-2',
  'file-clock',
  'file-code',
  'file-code-2',
  'file-cog',
  'file-diff',
  'file-digit',
  'file-down',
  'file-edit',
  'file-exclamation-point',
  'file-heart',
  'file-image',
  'file-input',
  'file-key',
  'file-lock',
  'file-minus',
  'file-minus-2',
  'file-music',
  'file-output',
  'file-pen-line',
  'file-play',
  'file-plus',
  'file-plus-2',
  'file-question',
  'file-scan',
  'file-search',
  'file-search-2',
  'file-signal',
  'file-sliders',
  'file-spreadsheet',
  'file-stack',
  'file-symlink',
  'file-terminal',
  'file-text',
  'file-type',
  'file-type-2',
  'file-up',
  'file-user',
  'file-video-2',
  'file-volume',
  'file-x',
  'file-x-2',
  'files',
  'film',
  'filter',
  'filter-x',
  'fingerprint',
  'fire-extinguisher',
  'fish',
  'fish-off',
  'fish-symbol',
  'fishing-hook',
  'fishing-rod',
  'flag',
  'flag-off',
  'flag-triangle-left',
  'flag-triangle-right',
  'flame',
  'flame-kindling',
  'flashlight',
  'flashlight-off',
  'flask-conical',
  'flask-conical-off',
  'flask-round',
  'flip-horizontal',
  'flip-horizontal-2',
  'flip-vertical',
  'flip-vertical-2',
  'flower',
  'flower-2',
  'focus',
  'fold-horizontal',
  'fold-vertical',
  'folder',
  'folder-archive',
  'folder-bookmark',
  'folder-check',
  'folder-clock',
  'folder-closed',
  'folder-code',
  'folder-cog',
  'folder-dot',
  'folder-down',
  'folder-edit',
  'folder-git',
  'folder-git-2',
  'folder-heart',
  'folder-input',
  'folder-kanban',
  'folder-key',
  'folder-lock',
  'folder-minus',
  'folder-open',
  'folder-open-dot',
  'folder-output',
  'folder-plus',
  'folder-root',
  'folder-search',
  'folder-search-2',
  'folder-symlink',
  'folder-sync',
  'folder-tree',
  'folder-up',
  'folder-x',
  'folders',
  'footprints',
  'fork-knife',
  'fork-knife-crossed',
  'forklift',
  'form',
  'form-input',
  'forward',
  'frame',
  'fuel',
  'fullscreen',
  'function-square',
  'funnel-plus',
  'galaxy',
  'gallery-horizontal',
  'gallery-horizontal-end',
  'gallery-thumbnails',
  'gallery-vertical',
  'gallery-vertical-end',
  'gamepad',
  'gamepad-2',
  'gamepad-directional',
  'gantt-chart-square',
  'gap-horizontal',
  'gap-vertical',
  'gauge',
  'gavel',
  'gem',
  'georgian-lari',
  'germ',
  'germ-off',
  'ghost',
  'gift',
  'git-branch',
  'git-branch-minus',
  'git-branch-plus',
  'git-commit',
  'git-commit-vertical',
  'git-compare',
  'git-compare-arrows',
  'git-fork',
  'git-graph',
  'git-merge',
  'git-merge-conflict',
  'git-pull-request',
  'git-pull-request-arrow',
  'git-pull-request-closed',
  'git-pull-request-create',
  'git-pull-request-create-arrow',
  'git-pull-request-draft',
  'glass-water',
  'glasses',
  'globe',
  'globe-check',
  'globe-code',
  'globe-lock',
  'globe-off',
  'globe-x',
  'goal',
  'gpu',
  'grab',
  'graduation-cap',
  'grape',
  'grid',
  'grid-2-x-2',
  'grid-2-x-2-check',
  'grid-2-x-2-plus',
  'grid-2-x-2-x',
  'grid-3x-2',
  'grip',
  'grip-horizontal',
  'grip-vertical',
  'group',
  'guitar',
  'ham',
  'hamburger',
  'hammer',
  'hand',
  'hand-coins',
  'hand-fist',
  'hand-heart',
  'hand-helping',
  'hand-metal',
  'hand-platter',
  'handbag',
  'handshake',
  'hard-drive',
  'hard-drive-download',
  'hard-drive-upload',
  'hard-hat',
  'hash',
  'hat-glasses',
  'haze',
  'hd',
  'hdmi-port',
  'heading',
  'heading-1',
  'heading-2',
  'heading-3',
  'heading-4',
  'heading-5',
  'heading-6',
  'headphone-off',
  'headphones',
  'headset',
  'heart',
  'heart-crack',
  'heart-handshake',
  'heart-minus',
  'heart-off',
  'heart-plus',
  'heart-pulse',
  'heart-x',
  'heater',
  'helicopter',
  'hexagon',
  'highlighter',
  'history',
  'home',
  'hop',
  'hop-off',
  'hospital',
  'hotel',
  'hourglass',
  'hourglass-cog',
  'house-cog',
  'house-heart',
  'house-plug',
  'house-plus',
  'house-wifi',
  'houses',
  'ice-cream',
  'ice-cream-2',
  'id-card',
  'id-card-lanyard',
  'image',
  'image-down',
  'image-minus',
  'image-off',
  'image-play',
  'image-plus',
  'image-up',
  'image-upscale',
  'images',
  'import',
  'inbox',
  'indent',
  'indent-decrease',
  'indian-rupee',
  'infinity',
  'info',
  'inspect',
  'inspection-panel',
  'italic',
  'iteration-ccw',
  'iteration-cw',
  'iv-bag',
  'japanese-yen',
  'joystick',
  'kanban',
  'kanban-square',
  'kanban-square-dashed',
  'kayak',
  'kazakh-tenge',
  'key',
  'key-round',
  'key-square',
  'keyboard',
  'keyboard-music',
  'keyboard-off',
  'lambda',
  'lamp',
  'lamp-ceiling',
  'lamp-desk',
  'lamp-floor',
  'lamp-wall-down',
  'lamp-wall-up',
  'land-plot',
  'landmark',
  'languages',
  'laptop',
  'laptop-2',
  'laptop-minimal-check',
  'lasso',
  'lasso-select',
  'layer-arrow-down',
  'layer-arrow-up',
  'layers',
  'layers-2',
  'layers-arrow-down',
  'layers-arrow-up',
  'layers-minus',
  'layers-plus',
  'layout',
  'layout-arrow-down',
  'layout-arrow-right',
  'layout-dashboard',
  'layout-freeform',
  'layout-grid',
  'layout-grid-circles',
  'layout-list',
  'layout-panel-left',
  'layout-panel-top',
  'layout-template',
  'leaf',
  'leafy-green',
  'lectern',
  'lens-concave',
  'lens-convex',
  'letter-text',
  'letters',
  'library',
  'library-big',
  'library-square',
  'life-buoy',
  'ligature',
  'lightbulb',
  'lightbulb-off',
  'lighthouse',
  'line-dot-bottom-vertical',
  'line-dot-left-horizontal',
  'line-dot-right-horizontal',
  'line-dot-top-vertical',
  'line-squiggle',
  'line-style',
  'link',
  'link-2',
  'link-2-off',
  'list',
  'list-check',
  'list-checks',
  'list-chevrons-down-up',
  'list-chevrons-up-down',
  'list-clock',
  'list-collapse',
  'list-end',
  'list-filter',
  'list-filter-plus',
  'list-minus',
  'list-music',
  'list-ordered',
  'list-plus',
  'list-restart',
  'list-sort-ascending',
  'list-sort-descending',
  'list-start',
  'list-todo',
  'list-tree',
  'list-video',
  'list-x',
  'loader',
  'loader-2',
  'loader-pinwheel',
  'locate',
  'locate-fixed',
  'locate-off',
  'location-edit',
  'lock',
  'lock-keyhole',
  'lock-keyhole-open',
  'lock-open',
  'log-in',
  'log-out',
  'logs',
  'lollipop',
  'luggage',
  'm-square',
  'magnet',
  'mail',
  'mail-badge',
  'mail-check',
  'mail-clock',
  'mail-minus',
  'mail-open',
  'mail-pen',
  'mail-plus',
  'mail-question',
  'mail-search',
  'mail-warning',
  'mail-x',
  'mailbox',
  'mails',
  'map',
  'map-minus',
  'map-pin',
  'map-pin-check',
  'map-pin-check-inside',
  'map-pin-house',
  'map-pin-minus',
  'map-pin-minus-inside',
  'map-pin-off',
  'map-pin-plus',
  'map-pin-plus-inside',
  'map-pin-search',
  'map-pin-x',
  'map-pin-x-inside',
  'map-pinned',
  'map-plus',
  'mars',
  'mars-stroke',
  'martini',
  'maximize',
  'maximize-2',
  'medal',
  'megaphone',
  'megaphone-off',
  'memory-stick',
  'menu',
  'menu-square',
  'merge',
  'message-circle',
  'message-circle-check',
  'message-circle-code',
  'message-circle-dashed',
  'message-circle-dashed-check',
  'message-circle-heart',
  'message-circle-more',
  'message-circle-off',
  'message-circle-plus',
  'message-circle-question',
  'message-circle-reply',
  'message-circle-warning',
  'message-circle-x',
  'message-square',
  'message-square-check',
  'message-square-code',
  'message-square-dashed',
  'message-square-diff',
  'message-square-dot',
  'message-square-heart',
  'message-square-lock',
  'message-square-more',
  'message-square-off',
  'message-square-plus',
  'message-square-quote',
  'message-square-reply',
  'message-square-share',
  'message-square-text',
  'message-square-warning',
  'message-square-x',
  'messages-circle',
  'messages-square',
  'metronome',
  'mic',
  'mic-2',
  'mic-audio-lines',
  'mic-off',
  'mic-signal',
  'microchip',
  'microscope',
  'microwave',
  'midi-port',
  'milestone',
  'milk',
  'milk-off',
  'minimize',
  'minimize-2',
  'minus',
  'minus-square',
  'mirror-rectangular',
  'mirror-round',
  'monitor',
  'monitor-check',
  'monitor-cloud',
  'monitor-cog',
  'monitor-dot',
  'monitor-down',
  'monitor-off',
  'monitor-pause',
  'monitor-pc',
  'monitor-play',
  'monitor-smartphone',
  'monitor-speaker',
  'monitor-stop',
  'monitor-up',
  'monitor-x',
  'moon',
  'moon-star',
  'mop',
  'mop-sparkles',
  'mosque',
  'motorbike',
  'mountain',
  'mountain-snow',
  'mouse',
  'mouse-left',
  'mouse-off',
  'mouse-pointer',
  'mouse-pointer-2',
  'mouse-pointer-2-off',
  'mouse-pointer-ban',
  'mouse-pointer-click',
  'mouse-pointer-square-dashed',
  'mouse-right',
  'mouth',
  'mouth-off',
  'move',
  'move-3-d',
  'move-diagonal',
  'move-diagonal-2',
  'move-down',
  'move-down-left',
  'move-down-right',
  'move-horizontal',
  'move-left',
  'move-right',
  'move-up',
  'move-up-left',
  'move-up-right',
  'move-vertical',
  'music',
  'music-2',
  'music-3',
  'music-4',
  'navigation',
  'navigation-2',
  'navigation-2-off',
  'navigation-off',
  'nepali-rupee',
  'network',
  'newspaper',
  'nfc',
  'non-binary',
  'notebook',
  'notebook-dot',
  'notebook-pen',
  'notebook-tabs',
  'notebook-text',
  'notepad-text',
  'notepad-text-dashed',
  'nut',
  'nut-off',
  'octagon',
  'octagon-minus',
  'octagon-pause',
  'octagon-x',
  'omega',
  'option',
  'orbit',
  'origami',
  'package',
  'package-2',
  'package-check',
  'package-minus',
  'package-open',
  'package-plus',
  'package-search',
  'package-x',
  'paint-bucket',
  'paint-roller',
  'paintbrush',
  'paintbrush-2',
  'palette',
  'palmtree',
  'panda',
  'panel-bottom',
  'panel-bottom-close',
  'panel-bottom-dashed',
  'panel-bottom-open',
  'panel-left',
  'panel-left-close',
  'panel-left-dashed',
  'panel-left-open',
  'panel-left-right-dashed',
  'panel-right',
  'panel-right-close',
  'panel-right-dashed',
  'panel-right-open',
  'panel-top',
  'panel-top-bottom-dashed',
  'panel-top-close',
  'panel-top-dashed',
  'panel-top-open',
  'panels-left-bottom',
  'panels-right-bottom',
  'panels-top-bottom',
  'paper-bag',
  'paperclip',
  'parasol',
  'parentheses',
  'park',
  'parking-meter',
  'parking-square',
  'parking-square-off',
  'party-popper',
  'pause',
  'paw-print',
  'pc-case',
  'pen-off',
  'pen-tool',
  'pencil',
  'pencil-line',
  'pencil-off',
  'pencil-ruler',
  'pencil-sparkles',
  'pentagon',
  'percent',
  'percent-square',
  'person-standing',
  'phi',
  'philippine-peso',
  'phone',
  'phone-call',
  'phone-forwarded',
  'phone-incoming',
  'phone-missed',
  'phone-off',
  'phone-outgoing',
  'pi',
  'pi-square',
  'piano',
  'pickaxe',
  'picture-in-picture',
  'picture-in-picture-2',
  'piggy-bank',
  'pilcrow',
  'pilcrow-left',
  'pilcrow-right',
  'pilcrow-square',
  'pill',
  'pill-bottle',
  'pin',
  'pin-off',
  'pipette',
  'pizza',
  'plane',
  'plane-landing',
  'plane-takeoff',
  'plant-pot',
  'play',
  'play-off',
  'play-square',
  'playing-card',
  'playing-cards',
  'playing-cards-fan',
  'plug',
  'plug-2',
  'plug-zap',
  'plus',
  'plus-square',
  'pocket-knife',
  'podium',
  'pointer',
  'pointer-off',
  'popcorn',
  'popsicle',
  'pound-sterling',
  'power',
  'power-off',
  'power-square',
  'presentation',
  'printer',
  'printer-3d',
  'printer-check',
  'printer-x',
  'projector',
  'proportions',
  'puzzle',
  'pyramid',
  'qr-code',
  'quote',
  'rabbit',
  'radar',
  'radiation',
  'radical',
  'radio',
  'radio-off',
  'radio-receiver',
  'radio-tower',
  'radius',
  'rainbow',
  'rat',
  'ratio',
  'receipt',
  'receipt-cent',
  'receipt-euro',
  'receipt-indian-rupee',
  'receipt-japanese-yen',
  'receipt-pound-sterling',
  'receipt-russian-ruble',
  'receipt-swiss-franc',
  'receipt-text',
  'receipt-turkish-lira',
  'rectangle-circle',
  'rectangle-goggles',
  'rectangle-horizontal',
  'rectangle-vertical',
  'recycle',
  'redo',
  'redo-2',
  'redo-dot',
  'refresh-ccw',
  'refresh-ccw-dot',
  'refresh-cw',
  'refresh-cw-off',
  'refrigerator',
  'regex',
  'remove-formatting',
  'repeat',
  'repeat-1',
  'repeat-2',
  'repeat-off',
  'replace',
  'replace-all',
  'reply',
  'reply-all',
  'rewind',
  'ribbon',
  'road',
  'robot-arm',
  'robot-vacuum',
  'rocket',
  'rocking-chair',
  'roller-coaster',
  'rose',
  'rotate-3-d',
  'rotate-ccw',
  'rotate-ccw-key',
  'rotate-ccw-square',
  'rotate-cw',
  'rotate-cw-clock',
  'rotate-cw-fading-clock',
  'rotate-cw-square',
  'route',
  'route-off',
  'router',
  'rows',
  'rows-4',
  'rss',
  'rugby-ball',
  'ruler',
  'ruler-dimension-line',
  'russian-ruble',
  'sailboat',
  'salad',
  'sandwich',
  'satellite',
  'satellite-dish',
  'saudi-riyal',
  'save',
  'save-all',
  'save-check',
  'save-off',
  'save-pen',
  'save-plus',
  'scale',
  'scale-3-d',
  'scaling',
  'scan',
  'scan-barcode',
  'scan-box',
  'scan-eye',
  'scan-face',
  'scan-heart',
  'scan-line',
  'scan-qr-code',
  'scan-search',
  'scan-square',
  'scan-text',
  'school',
  'school-2',
  'scissors',
  'scissors-line-dashed',
  'scissors-square',
  'scissors-square-dashed-bottom',
  'scooter',
  'screen-share',
  'screen-share-off',
  'scroll',
  'scroll-text',
  'search',
  'search-alert',
  'search-check',
  'search-code',
  'search-slash',
  'search-x',
  'section',
  'send',
  'send-horizonal',
  'send-to-back',
  'separator-horizontal',
  'separator-vertical',
  'server',
  'server-cog',
  'server-crash',
  'server-off',
  'server-plus',
  'settings',
  'settings-2',
  'shapes',
  'share',
  'share-2',
  'sheet',
  'shell',
  'shelving-unit',
  'shield',
  'shield-alert',
  'shield-ban',
  'shield-check',
  'shield-close',
  'shield-cog',
  'shield-cog-corner',
  'shield-ellipsis',
  'shield-half',
  'shield-keyhole',
  'shield-lock',
  'shield-minus',
  'shield-off',
  'shield-plus',
  'shield-question',
  'shield-user',
  'ship',
  'ship-cargo',
  'ship-wheel',
  'shirt',
  'shopping-bag',
  'shopping-basket',
  'shopping-cart',
  'shopping-cart-minus',
  'shopping-cart-plus',
  'shovel',
  'shower-head',
  'shredder',
  'shrimp',
  'shrimp-off',
  'shrink',
  'shrub',
  'shuffle',
  'sigma',
  'sigma-square',
  'signal',
  'signal-high',
  'signal-low',
  'signal-medium',
  'signal-zero',
  'signature',
  'signpost',
  'signpost-big',
  'siren',
  'skip-back',
  'skip-forward',
  'skull',
  'slash',
  'slash-square',
  'slice',
  'sliders',
  'sliders-horizontal',
  'smartphone',
  'smartphone-charging',
  'smartphone-nfc',
  'snail',
  'snowflake',
  'soap-dispenser-droplet',
  'sofa',
  'solar-panel',
  'soup',
  'space',
  'spade',
  'sparkle',
  'sparkles',
  'speaker',
  'speech',
  'spell-check',
  'spell-check-2',
  'spline',
  'spline-pointer',
  'split',
  'split-square-horizontal',
  'split-square-vertical',
  'spool',
  'sport-shoe',
  'spotlight',
  'spray-can',
  'sprout',
  'square',
  'square-arrow-right-enter',
  'square-arrow-right-exit',
  'square-dashed-bottom',
  'square-dashed-bottom-code',
  'square-dashed-plus',
  'square-dashed-text',
  'square-dashed-top-solid',
  'square-dashed-x',
  'square-dashed-x-corner',
  'square-dimensions',
  'square-exclamation-point',
  'square-off',
  'square-pause',
  'square-radical',
  'square-round-corner',
  'square-sparkles',
  'square-square',
  'square-stack',
  'square-star',
  'square-stop',
  'square-terminal',
  'square-text',
  'square-user',
  'square-user-round',
  'square-x',
  'squares-exclude',
  'squares-intersect',
  'squares-subtract',
  'squares-unite',
  'squircle',
  'squircle-dashed',
  'squirrel',
  'stamp',
  'star',
  'star-check',
  'star-half',
  'star-minus',
  'star-off',
  'star-plus',
  'star-x',
  'step-back',
  'step-forward',
  'stethoscope',
  'sticker',
  'sticky-note',
  'sticky-note-check',
  'sticky-note-minus',
  'sticky-note-off',
  'sticky-note-plus',
  'sticky-note-x',
  'sticky-notes',
  'stone',
  'store',
  'stretch-horizontal',
  'stretch-vertical',
  'strikethrough',
  'subscript',
  'summary',
  'sun',
  'sun-dim',
  'sun-medium',
  'sun-moon',
  'sun-snow',
  'sunrise',
  'sunset',
  'superscript',
  'swatch-book',
  'swiss-franc',
  'switch-camera',
  'sword',
  'swords',
  'syringe',
  'table',
  'table-2',
  'table-cells-merge',
  'table-cells-split',
  'table-columns-split',
  'table-of-contents',
  'table-properties',
  'table-rows-split',
  'tablet',
  'tablet-smartphone',
  'tablets',
  'tag',
  'tag-plus',
  'tag-x',
  'tags',
  'tally-1',
  'tally-2',
  'tally-3',
  'tally-4',
  'tally-5',
  'tangent',
  'target',
  'telescope',
  'tent',
  'tent-tree',
  'terminal',
  'test-tube',
  'test-tube-2',
  'test-tubes',
  'text-align-justify-center',
  'text-align-justify-end',
  'text-align-justify-start',
  'text-cursor',
  'text-cursor-input',
  'text-quote',
  'text-search',
  'text-wrap',
  'theater',
  'thermometer',
  'thermometer-snowflake',
  'thermometer-sun',
  'thumbs-down',
  'thumbs-up',
  'tic-tac-toe',
  'ticket',
  'ticket-check',
  'ticket-minus',
  'ticket-percent',
  'ticket-plus',
  'ticket-slash',
  'ticket-x',
  'tickets',
  'tickets-plane',
  'timeline',
  'timer',
  'timer-off',
  'timer-reset',
  'toggle-left',
  'toggle-right',
  'toilet',
  'tool-case',
  'toolbox',
  'toothbrush',
  'toothbrush-sparkles',
  'tornado',
  'torus',
  'touchpad',
  'touchpad-off',
  'towel-rack',
  'tower-control',
  'toy-brick',
  'tractor',
  'traffic-cone',
  'trailer',
  'train',
  'train-front',
  'train-front-tunnel',
  'train-track',
  'transgender',
  'trash',
  'trash-off',
  'tree-deciduous',
  'tree-pine',
  'trees',
  'trending-down',
  'trending-up',
  'trending-up-down',
  'triangle',
  'triangle-dashed',
  'triangle-right',
  'trophy',
  'truck',
  'truck-electric',
  'tube-lotion',
  'turkish-lira',
  'turntable',
  'turtle',
  'tv',
  'tv-2',
  'tv-minimal-play',
  'type',
  'type-outline',
  'umbrella',
  'umbrella-off',
  'underline',
  'undo',
  'undo-2',
  'undo-dot',
  'unfold-horizontal',
  'unfold-vertical',
  'ungroup',
  'unlink',
  'unlink-2',
  'unplug',
  'upload',
  'usb',
  'usb-c-port',
  'user',
  'user-2',
  'user-check',
  'user-check-2',
  'user-cog',
  'user-cog-2',
  'user-group',
  'user-key',
  'user-lock',
  'user-minus',
  'user-minus-2',
  'user-pen',
  'user-plus',
  'user-plus-2',
  'user-round-arrow-left',
  'user-round-group',
  'user-round-key',
  'user-round-pen',
  'user-round-search',
  'user-round-x',
  'user-search',
  'user-shield',
  'user-star',
  'user-x',
  'users',
  'users-2',
  'utility-pole',
  'van',
  'variable',
  'vault',
  'vector-polygon',
  'vector-square',
  'vegan',
  'venetian-mask',
  'venus',
  'venus-and-mars',
  'vibrate',
  'vibrate-off',
  'video',
  'video-off',
  'videotape',
  'view',
  'virus',
  'virus-off',
  'voicemail',
  'volleyball',
  'volume',
  'volume-1',
  'volume-2',
  'volume-off',
  'volume-x',
  'vote',
  'wallet',
  'wallet-2',
  'wallet-cards',
  'wallpaper',
  'wand',
  'wand-2',
  'warehouse',
  'washing-machine',
  'watch',
  'waves',
  'waves-arrow-down',
  'waves-arrow-up',
  'waves-ladder',
  'waves-vertical',
  'waypoints',
  'webcam',
  'webcam-off',
  'webhook',
  'webhook-off',
  'weight',
  'weight-tilde',
  'wheat',
  'wheat-off',
  'whistle',
  'whole-word',
  'wifi',
  'wifi-cog',
  'wifi-high',
  'wifi-low',
  'wifi-off',
  'wifi-pen',
  'wifi-sync',
  'wifi-zero',
  'wind',
  'wind-arrow-down',
  'wind-arrow-up',
  'wine',
  'wine-off',
  'workflow',
  'worm',
  'wrench',
  'wrench-off',
  'x',
  'x-line-top',
  'zap',
  'zap-off',
  'zodiac-aquarius',
  'zodiac-aries',
  'zodiac-cancer',
  'zodiac-capricorn',
  'zodiac-gemini',
  'zodiac-leo',
  'zodiac-libra',
  'zodiac-ophiuchus',
  'zodiac-pisces',
  'zodiac-sagittarius',
  'zodiac-scorpio',
  'zodiac-taurus',
  'zodiac-virgo',
  'zoom-in',
  'zoom-out',
];

const ICON_LIBRARY_NAME_SET: ReadonlySet<string> = new Set(ICON_LIBRARY_NAMES);

/** Является ли строка именем иконки каталога Lucide (kebab-case). */
export function isIconLibraryName(value: string): boolean {
  return ICON_LIBRARY_NAME_SET.has(value);
}

/**
 * Псевдонимы kebab-имён Lucide: псевдоним → каноническое kebab-имя той же
 * геометрии (ошибка 08b90470). Псевдонимы, совпавшие с каноническим именем,
 * опущены — каноническое имя приоритетнее.
 */
export const ICON_LIBRARY_ALIASES: Readonly<Record<string, string>> = {
  'alarm-clock-check': 'alarm-check',
  'alarm-minus': 'alarm-clock-minus',
  'alarm-plus': 'alarm-clock-plus',
  'axis-3d': 'axis-3-d',
  'badge-question-mark': 'badge-help',
  'between-horizontal-end': 'between-horizonal-end',
  'between-horizontal-start': 'between-horizonal-start',
  'book-marked': 'book-bookmark',
  'book-template': 'book-dashed',
  'building-complex': 'building-2',
  'chart-area': 'area-chart',
  'chart-bar': 'bar-chart-horizontal',
  'chart-bar-big': 'bar-chart-horizontal-big',
  'chart-candlestick': 'candlestick-chart',
  'chart-column': 'bar-chart-3',
  'chart-column-big': 'bar-chart-big',
  'chart-column-increasing': 'bar-chart-4',
  'chart-no-axes-column': 'bar-chart-2',
  'chart-no-axes-column-increasing': 'bar-chart',
  'circle-alert': 'alert-circle',
  'circle-arrow-down': 'arrow-down-circle',
  'circle-arrow-left': 'arrow-left-circle',
  'circle-arrow-out-down-left': 'arrow-down-left-from-circle',
  'circle-arrow-out-down-right': 'arrow-down-right-from-circle',
  'circle-arrow-out-up-left': 'arrow-up-left-from-circle',
  'circle-arrow-out-up-right': 'arrow-up-right-from-circle',
  'circle-arrow-right': 'arrow-right-circle',
  'circle-arrow-up': 'arrow-up-circle',
  'circle-check': 'check-circle-2',
  'circle-check-big': 'check-circle',
  'circle-chevron-down': 'chevron-down-circle',
  'circle-chevron-left': 'chevron-left-circle',
  'circle-chevron-right': 'chevron-right-circle',
  'circle-chevron-up': 'chevron-up-circle',
  'circle-question-mark': 'circle-help',
  'circle-slashed': 'circle-slash-2',
  'clipboard-pen': 'clipboard-edit',
  'clipboard-signature': 'clipboard-pen-line',
  'code-xml': 'code-2',
  'columns-2': 'columns',
  'columns-settings': 'columns-3-cog',
  'contact-round': 'contact-2',
  'curly-braces': 'braces',
  'divide-circle': 'circle-divide',
  'download-cloud': 'cloud-download',
  'face-angry': 'angry',
  'face-expressionless': 'annoyed',
  'file-audio-2': 'file-audio',
  'file-axis-3d': 'file-axis-3-d',
  'file-badge-2': 'file-badge',
  'file-chart-column': 'file-bar-chart-2',
  'file-chart-column-increasing': 'file-bar-chart',
  'file-check-corner': 'file-check-2',
  'file-code-corner': 'file-code-2',
  'file-cog-2': 'file-cog',
  'file-headphone': 'file-audio',
  'file-json': 'file-braces',
  'file-json-2': 'file-braces-corner',
  'file-key-2': 'file-key',
  'file-line-chart': 'file-chart-line',
  'file-lock-2': 'file-lock',
  'file-minus-corner': 'file-minus-2',
  'file-pen': 'file-edit',
  'file-pie-chart': 'file-chart-pie',
  'file-plus-corner': 'file-plus-2',
  'file-question-mark': 'file-question',
  'file-search-corner': 'file-search-2',
  'file-signature': 'file-pen-line',
  'file-type-corner': 'file-type-2',
  'file-video': 'file-play',
  'file-video-camera': 'file-video-2',
  'file-volume-2': 'file-signal',
  'file-warning': 'file-exclamation-point',
  'file-x-corner': 'file-x-2',
  'fingerprint-pattern': 'fingerprint',
  'folder-cog-2': 'folder-cog',
  'folder-pen': 'folder-edit',
  'frown': 'face-slightly-frowning',
  'funnel': 'filter',
  'funnel-x': 'filter-x',
  'gantt-chart': 'chart-no-axes-gantt',
  'gauge-circle': 'circle-gauge',
  'git-commit-horizontal': 'git-commit',
  'globe-2': 'earth',
  'grid-2x-2': 'grid-2-x-2',
  'grid-2x-2-check': 'grid-2-x-2-check',
  'grid-2x-2-plus': 'grid-2-x-2-plus',
  'grid-2x-2-x': 'grid-2-x-2-x',
  'grid-3-x-3': 'grid',
  'grid-3x-3': 'grid',
  'hand-grab': 'grab',
  'help-circle': 'circle-help',
  'helping-hand': 'hand-helping',
  'house': 'home',
  'ice-cream-bowl': 'ice-cream-2',
  'ice-cream-cone': 'ice-cream',
  'indent-increase': 'indent',
  'laptop-minimal': 'laptop-2',
  'laugh': 'face-grinning',
  'layers-3': 'layers',
  'line-chart': 'chart-line',
  'list-indent-decrease': 'indent-decrease',
  'list-indent-increase': 'indent',
  'loader-circle': 'loader-2',
  'mail-question-mark': 'mail-question',
  'map-pin-pen': 'location-edit',
  'meh': 'face-neutral',
  'message-circle-question-mark': 'message-circle-question',
  'mic-vocal': 'mic-2',
  'minus-circle': 'circle-minus',
  'more-horizontal': 'ellipsis',
  'more-vertical': 'ellipsis-vertical',
  'move-3d': 'move-3-d',
  'octagon-alert': 'alert-octagon',
  'outdent': 'indent-decrease',
  'paintbrush-vertical': 'paintbrush-2',
  'panel-bottom-inactive': 'panel-bottom-dashed',
  'panel-left-inactive': 'panel-left-dashed',
  'panel-right-inactive': 'panel-right-dashed',
  'panel-top-inactive': 'panel-top-dashed',
  'panels-left-right': 'columns-3',
  'panels-top-left': 'layout',
  'parking-circle': 'circle-parking',
  'parking-circle-off': 'circle-parking-off',
  'pause-circle': 'circle-pause',
  'pause-octagon': 'octagon-pause',
  'pen': 'edit-2',
  'pen-box': 'edit',
  'pen-line': 'edit-3',
  'pen-square': 'edit',
  'percent-circle': 'circle-percent',
  'percent-diamond': 'diamond-percent',
  'pie-chart': 'chart-pie',
  'play-circle': 'circle-play',
  'plug-zap-2': 'plug-zap',
  'plus-circle': 'circle-plus',
  'podcast': 'mic-signal',
  'power-circle': 'circle-power',
  'rectangle-ellipsis': 'form-input',
  'rotate-3d': 'rotate-3-d',
  'rotate-ccw-clock': 'history',
  'rows-2': 'rows',
  'rows-3': 'panels-top-bottom',
  'scale-3d': 'scale-3-d',
  'scatter-chart': 'chart-scatter',
  'send-horizontal': 'send-horizonal',
  'shield-question-mark': 'shield-question',
  'shield-x': 'shield-close',
  'sidebar': 'panel-left',
  'sidebar-close': 'panel-left-close',
  'sidebar-open': 'panel-left-open',
  'sliders-vertical': 'sliders',
  'smile': 'face-slightly-smiling',
  'smile-plus': 'face-slightly-smiling-plus',
  'sort-asc': 'arrow-up-narrow-wide',
  'sort-desc': 'arrow-down-wide-narrow',
  'square-activity': 'activity-square',
  'square-arrow-down': 'arrow-down-square',
  'square-arrow-down-left': 'arrow-down-left-square',
  'square-arrow-down-right': 'arrow-down-right-square',
  'square-arrow-left': 'arrow-left-square',
  'square-arrow-out-down-left': 'arrow-down-left-from-square',
  'square-arrow-out-down-right': 'arrow-down-right-from-square',
  'square-arrow-out-up-left': 'arrow-up-left-from-square',
  'square-arrow-out-up-right': 'arrow-up-right-from-square',
  'square-arrow-right': 'arrow-right-square',
  'square-arrow-up': 'arrow-up-square',
  'square-arrow-up-left': 'arrow-up-left-square',
  'square-arrow-up-right': 'arrow-up-right-square',
  'square-asterisk': 'asterisk-square',
  'square-bookmark': 'album',
  'square-bottom-dashed-scissors': 'scissors-square-dashed-bottom',
  'square-centerline-dashed-horizontal': 'flip-horizontal',
  'square-centerline-dashed-vertical': 'flip-vertical',
  'square-chart-gantt': 'gantt-chart-square',
  'square-check': 'check-square-2',
  'square-check-big': 'check-square',
  'square-chevron-down': 'chevron-down-square',
  'square-chevron-left': 'chevron-left-square',
  'square-chevron-right': 'chevron-right-square',
  'square-chevron-up': 'chevron-up-square',
  'square-code': 'code-square',
  'square-dashed': 'box-select',
  'square-dashed-kanban': 'kanban-square-dashed',
  'square-dashed-mouse-pointer': 'mouse-pointer-square-dashed',
  'square-divide': 'divide-square',
  'square-dot': 'dot-square',
  'square-equal': 'equal-square',
  'square-function': 'function-square',
  'square-gantt-chart': 'gantt-chart-square',
  'square-kanban': 'kanban-square',
  'square-library': 'library-square',
  'square-m': 'm-square',
  'square-menu': 'menu-square',
  'square-minus': 'minus-square',
  'square-mouse-pointer': 'inspect',
  'square-parking': 'parking-square',
  'square-parking-off': 'parking-square-off',
  'square-pen': 'edit',
  'square-percent': 'percent-square',
  'square-pi': 'pi-square',
  'square-pilcrow': 'pilcrow-square',
  'square-play': 'play-square',
  'square-plus': 'plus-square',
  'square-power': 'power-square',
  'square-scissors': 'scissors-square',
  'square-sigma': 'sigma-square',
  'square-slash': 'slash-square',
  'square-split-horizontal': 'split-square-horizontal',
  'square-split-vertical': 'split-square-vertical',
  'stars': 'sparkles',
  'stop-circle': 'circle-stop',
  'subtitles': 'captions',
  'table-config': 'columns-3-cog',
  'terminal-square': 'square-terminal',
  'test-tube-diagonal': 'test-tube-2',
  'text': 'align-left',
  'text-align-center': 'align-center',
  'text-align-end': 'align-right',
  'text-align-justify': 'align-justify',
  'text-align-start': 'align-left',
  'text-initial': 'letter-text',
  'text-select': 'square-dashed-text',
  'text-selection': 'square-dashed-text',
  'tram-front': 'train',
  'trash-2': 'trash',
  'tree-palm': 'palmtree',
  'triangle-alert': 'alert-triangle',
  'triangles-centerline-dashed-horizontal': 'flip-horizontal-2',
  'triangles-centerline-dashed-vertical': 'flip-vertical-2',
  'tv-minimal': 'tv-2',
  'university': 'school-2',
  'unlock': 'lock-open',
  'unlock-keyhole': 'lock-keyhole-open',
  'upload-cloud': 'cloud-upload',
  'user-circle': 'circle-user',
  'user-circle-2': 'circle-user-round',
  'user-round': 'user-2',
  'user-round-check': 'user-check-2',
  'user-round-cog': 'user-cog-2',
  'user-round-minus': 'user-minus-2',
  'user-round-plus': 'user-plus-2',
  'user-square': 'square-user',
  'user-square-2': 'square-user-round',
  'user-x-2': 'user-round-x',
  'users-round': 'users-2',
  'utensils': 'fork-knife',
  'utensils-crossed': 'fork-knife-crossed',
  'verified': 'badge-check',
  'wallet-minimal': 'wallet-2',
  'wand-sparkles': 'wand-2',
  'waves-horizontal': 'waves',
  'wrap-text': 'text-wrap',
  'x-circle': 'circle-x',
  'x-octagon': 'octagon-x',
  'x-square': 'square-x',
};

/**
 * Каноническое kebab-имя значка по каноническому имени ИЛИ псевдониму;
 * null — строки нет среди имён и псевдонимов Lucide. Псевдонимы нужны для
 * ПОИСКА; хранить и валидировать следует только канонические имена.
 */
export function canonicalIconLibraryName(value: string): string | null {
  if (ICON_LIBRARY_NAME_SET.has(value)) return value;
  if (!Object.prototype.hasOwnProperty.call(ICON_LIBRARY_ALIASES, value)) return null;
  return ICON_LIBRARY_ALIASES[value] ?? null;
}
